name: BuildAndPushImageOnHarbor

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: login hub.wilfredalmeida.com
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t hub.wilfredalmeida.com/email-generator/email-gen-img:${{ github.run_number }}
        docker push hub.wilfredalmeida.com/email-generator/email-gen-img:${{ github.run_number }}
